-- ══════════════════════════════════════════════════════════════════
--  Digital CS Onboarding Dashboard — Supabase Backend
--  Matches index.html exactly: progress, timestamps, toolAccess, tokens
--
--  HOW TO RUN:
--  Supabase Dashboard → SQL Editor → New query → paste → Run
-- ══════════════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────────────
--  STEP 1 — TABLES
-- ──────────────────────────────────────────────────────────────────

-- ── dcs_progress ─────────────────────────────────────────────────
-- Stores all three JSONB blobs the dashboard syncs:
--
--   progress    → { "week1-0": true, "week1-2": false, ... }
--                 Set by toggleTask(). Key = "<weekId>-<taskIndex>".
--                 Value = boolean (true = done).
--
--   timestamps  → { "week1-0": { startedAt: 1718000000000, completedAt: 1718003600000 }, ... }
--                 Set by toggleTask() and startTask().
--                 Epoch ms integers matching JS Date.now().
--
--   tool_access → { "Salesforce": "granted", "Amplitude": "pending", ... }
--                 Set by the Tools tab dropdown.
--                 Values are always "granted" or "pending".
--
-- Single singleton row — the dashboard always upserts id = 'singleton'.
create table if not exists dcs_progress (
  id           text        primary key default 'singleton',
  progress     jsonb       not null default '{}',
  timestamps   jsonb       not null default '{}',
  tool_access  jsonb       not null default '{}',
  updated_at   timestamptz not null default now()
);

-- Seed the singleton so the first upsert always has a row to merge into.
insert into dcs_progress (id, progress, timestamps, tool_access)
values ('singleton', '{}', '{}', '{}')
on conflict (id) do nothing;


-- ── dcs_tokens ───────────────────────────────────────────────────
-- Share tokens generated by the owner via the Share modal.
-- The dashboard creates a token with genToken() (format: XXXXXXXX-XXXXXXXX)
-- and calls SB.addToken(token). Viewers enter the token on the login screen.
-- Revoking calls SB.deleteToken(token).
create table if not exists dcs_tokens (
  token       text        primary key,
  created_at  timestamptz not null default now(),
  label       text        -- optional human note (not used by dashboard yet)
);


-- ── dcs_audit ────────────────────────────────────────────────────
-- Automatic history of every state change. Written only by triggers,
-- never directly by the dashboard.
create table if not exists dcs_audit (
  id          bigserial   primary key,
  event_type  text        not null,
  -- task_toggled  → a task was checked or unchecked
  -- task_started  → startedAt was recorded for a task
  -- tool_updated  → a tool's access status changed
  -- token_created → a share token was added
  -- token_revoked → a share token was deleted
  task_key    text,       -- e.g. "week1-2"  (null for token events)
  tool_name   text,       -- e.g. "Salesforce" (null for task/token events)
  old_value   jsonb,
  new_value   jsonb,
  created_at  timestamptz not null default now()
);


-- ──────────────────────────────────────────────────────────────────
--  STEP 2 — INDEXES
-- ──────────────────────────────────────────────────────────────────
create index if not exists dcs_audit_event_type_idx  on dcs_audit (event_type);
create index if not exists dcs_audit_created_at_idx  on dcs_audit (created_at desc);
create index if not exists dcs_audit_task_key_idx    on dcs_audit (task_key)    where task_key  is not null;
create index if not exists dcs_audit_tool_name_idx   on dcs_audit (tool_name)   where tool_name is not null;
create index if not exists dcs_tokens_created_at_idx on dcs_tokens (created_at asc);


-- ──────────────────────────────────────────────────────────────────
--  STEP 3 — UPDATED_AT TRIGGER
-- ──────────────────────────────────────────────────────────────────
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists dcs_progress_updated_at on dcs_progress;
create trigger dcs_progress_updated_at
  before update on dcs_progress
  for each row execute function set_updated_at();


-- ──────────────────────────────────────────────────────────────────
--  STEP 4 — AUDIT TRIGGER
--  Fires after every UPDATE to dcs_progress.
--  Detects exactly the three kinds of changes the dashboard makes:
--    1. progress key toggled        → event_type = 'task_toggled'
--    2. timestamps.startedAt added  → event_type = 'task_started'
--    3. tool_access value changed   → event_type = 'tool_updated'
-- ──────────────────────────────────────────────────────────────────
create or replace function log_progress_change()
returns trigger language plpgsql as $$
declare
  old_prog  jsonb := coalesce(old.progress,    '{}');
  new_prog  jsonb := coalesce(new.progress,    '{}');
  old_ts    jsonb := coalesce(old.timestamps,  '{}');
  new_ts    jsonb := coalesce(new.timestamps,  '{}');
  old_ta    jsonb := coalesce(old.tool_access, '{}');
  new_ta    jsonb := coalesce(new.tool_access, '{}');
  k         text;
  old_done  boolean;
  new_done  boolean;
  old_start bigint;
  new_start bigint;
  old_status text;
  new_status text;
begin

  -- ── 1. Task toggled (progress key changed) ────────────────────
  for k in
    select distinct key from (
      select jsonb_object_keys(old_prog) as key
      union
      select jsonb_object_keys(new_prog) as key
    ) keys
  loop
    old_done := coalesce((old_prog ->> k)::boolean, false);
    new_done := coalesce((new_prog ->> k)::boolean, false);
    if old_done is distinct from new_done then
      insert into dcs_audit (event_type, task_key, old_value, new_value)
      values (
        'task_toggled', k,
        jsonb_build_object(
          'done',       old_done,
          'startedAt',  (old_ts -> k ->> 'startedAt')::bigint,
          'completedAt',(old_ts -> k ->> 'completedAt')::bigint
        ),
        jsonb_build_object(
          'done',       new_done,
          'startedAt',  (new_ts -> k ->> 'startedAt')::bigint,
          'completedAt',(new_ts -> k ->> 'completedAt')::bigint
        )
      );
    end if;
  end loop;

  -- ── 2. Task started (startedAt newly set) ────────────────────
  for k in select jsonb_object_keys(new_ts) loop
    old_start := (old_ts -> k ->> 'startedAt')::bigint;
    new_start := (new_ts -> k ->> 'startedAt')::bigint;
    if old_start is null and new_start is not null then
      insert into dcs_audit (event_type, task_key, old_value, new_value)
      values (
        'task_started', k,
        jsonb_build_object('startedAt', null),
        jsonb_build_object('startedAt', new_start)
      );
    end if;
  end loop;

  -- ── 3. Tool access status changed ────────────────────────────
  for k in
    select distinct key from (
      select jsonb_object_keys(old_ta) as key
      union
      select jsonb_object_keys(new_ta) as key
    ) keys
  loop
    old_status := old_ta ->> k;
    new_status := new_ta ->> k;
    if old_status is distinct from new_status then
      insert into dcs_audit (event_type, tool_name, old_value, new_value)
      values (
        'tool_updated', k,
        jsonb_build_object('access', old_status),
        jsonb_build_object('access', new_status)
      );
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists dcs_progress_audit on dcs_progress;
create trigger dcs_progress_audit
  after update on dcs_progress
  for each row execute function log_progress_change();


-- ──────────────────────────────────────────────────────────────────
--  STEP 5 — TOKEN AUDIT TRIGGER
--  Logs token creation and revocation to dcs_audit.
-- ──────────────────────────────────────────────────────────────────
create or replace function log_token_change()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    insert into dcs_audit (event_type, old_value, new_value)
    values ('token_created', null, jsonb_build_object('token', new.token, 'created_at', new.created_at));
  elsif tg_op = 'DELETE' then
    insert into dcs_audit (event_type, old_value, new_value)
    values ('token_revoked', jsonb_build_object('token', old.token, 'created_at', old.created_at), null);
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists dcs_tokens_audit on dcs_tokens;
create trigger dcs_tokens_audit
  after insert or delete on dcs_tokens
  for each row execute function log_token_change();


-- ──────────────────────────────────────────────────────────────────
--  STEP 6 — ROW LEVEL SECURITY (RLS)
--  The dashboard uses the anon key only. These policies give it
--  exactly the permissions it needs — no more.
-- ──────────────────────────────────────────────────────────────────
alter table dcs_progress enable row level security;
alter table dcs_tokens   enable row level security;
alter table dcs_audit    enable row level security;

-- dcs_progress: anon can read and upsert (dashboard never deletes this row)
drop policy if exists "anon read progress" on dcs_progress;
create policy "anon read progress"
  on dcs_progress for select to anon using (true);

drop policy if exists "anon insert progress" on dcs_progress;
create policy "anon insert progress"
  on dcs_progress for insert to anon with check (true);

drop policy if exists "anon update progress" on dcs_progress;
create policy "anon update progress"
  on dcs_progress for update to anon using (true);

-- dcs_tokens: anon can read, insert, delete (needed for revoke)
drop policy if exists "anon read tokens" on dcs_tokens;
create policy "anon read tokens"
  on dcs_tokens for select to anon using (true);

drop policy if exists "anon insert tokens" on dcs_tokens;
create policy "anon insert tokens"
  on dcs_tokens for insert to anon with check (true);

drop policy if exists "anon delete tokens" on dcs_tokens;
create policy "anon delete tokens"
  on dcs_tokens for delete to anon using (true);

-- dcs_audit: anon read-only (written only by triggers)
drop policy if exists "anon read audit" on dcs_audit;
create policy "anon read audit"
  on dcs_audit for select to anon using (true);


-- ──────────────────────────────────────────────────────────────────
--  STEP 7 — REPORTING VIEWS
-- ──────────────────────────────────────────────────────────────────

-- Flat view of every task — mirrors the dashboard's TASKS constant.
-- task_key format: "week1-0", "week1-1" … "week3-3"
create or replace view dcs_task_status as
select
  entry.key                                                        as task_key,
  split_part(entry.key, '-', 1)                                    as week,
  split_part(entry.key, '-', 2)::int                               as task_index,
  coalesce((p.progress ->> entry.key)::boolean, false)             as is_done,
  to_timestamp(
    ((p.timestamps -> entry.key ->> 'startedAt')::bigint) / 1000.0
  )                                                                as started_at,
  to_timestamp(
    ((p.timestamps -> entry.key ->> 'completedAt')::bigint) / 1000.0
  )                                                                as completed_at,
  round(
    (
      ((p.timestamps -> entry.key ->> 'completedAt')::bigint) -
      ((p.timestamps -> entry.key ->> 'startedAt')::bigint)
    ) / 60000.0, 1
  )                                                                as duration_minutes,
  p.updated_at                                                     as last_saved
from dcs_progress p,
     jsonb_each(p.progress) as entry(key, value)
where p.id = 'singleton';


-- Tool access status — one row per tool that has been touched.
create or replace view dcs_tool_status as
select
  entry.key   as tool_name,
  entry.value #>> '{}' as access_status   -- "granted" or "pending"
from dcs_progress p,
     jsonb_each(p.tool_access) as entry(key, value)
where p.id = 'singleton';


-- Full audit log, most recent first.
create or replace view dcs_audit_log as
select
  id,
  event_type,
  coalesce(task_key, tool_name) as subject,
  old_value,
  new_value,
  created_at
from dcs_audit
order by created_at desc;


-- ──────────────────────────────────────────────────────────────────
--  STEP 8 — VERIFY
--  Run this after the above — should return 3 rows, all count = 1 or 0.
-- ──────────────────────────────────────────────────────────────────
select 'dcs_progress' as table_name, count(*) as row_count from dcs_progress
union all
select 'dcs_tokens',                 count(*)               from dcs_tokens
union all
select 'dcs_audit',                  count(*)               from dcs_audit;


-- ──────────────────────────────────────────────────────────────────
--  REFERENCE — Useful queries for monitoring / debugging
-- ──────────────────────────────────────────────────────────────────

-- See all task statuses:
--   select * from dcs_task_status order by week, task_index;

-- See completed tasks only:
--   select * from dcs_task_status where is_done = true order by completed_at;

-- See tasks still not started:
--   select task_key from dcs_task_status where started_at is null;

-- Average completion time per week:
--   select week, round(avg(duration_minutes),1) as avg_mins
--   from dcs_task_status
--   where duration_minutes is not null
--   group by week order by week;

-- See all tool access statuses:
--   select * from dcs_tool_status;

-- Full audit history:
--   select * from dcs_audit_log limit 100;

-- Count events by type:
--   select event_type, count(*) from dcs_audit group by event_type order by count desc;

-- See all active share tokens:
--   select token, created_at from dcs_tokens order by created_at;

-- Raw progress blob (what the dashboard reads/writes):
--   select progress, timestamps, tool_access, updated_at from dcs_progress where id = 'singleton';


